### ISSUE TITLE
Share Image

### ISSUE THREAD

**Issue by AppFolioRopes** [AppFolioOnboarding/image-sharer-mqchau#10]
#### As a user I want to share an image with someone via email.

__Story__:

This application is called Image Sharer. Sure, you can share images by adding
them to our web service, but how will people who do not know about this web
service be able to see those images? In phone calls with our customers we have
discovered that many of our users are manually emailing their friends links to
the images. That is awesome! We can make things more efficent for our users by
directly supporting sharing images through email.

__Acceptance criteria__:
- [ ] There is a link to share an image.
- [ ] After clicking on this link, a bootstrap modal appears with a form to
  send the email.
- [ ] The form has fields for the recipient's email and an optional message.
- [ ] The email we send has an HTML part and a text part.
- [ ] The email contains the image, the custom message if provided, and a link
  inviting the recipient to check out our application.
- [ ] The modal closes and a success message is shown if the email was sent
  successfully.
- [ ] The user is alerted of errors if the operation was unsuccessful.

__Note__: This story is large, so it makes sense to break the implementation
down into more manageable pieces (a la elephant carpaccio). Please start by
implementing a basic sharing feature that uses a new page (not a modal), and
open a PR for that. Then, once we've verified the simplified version is
working, refactor it to use a modal, and open a second PR for that. The
[video](https://sites.google.com/a/appfolio.com/eng/new-hire-resources/engineering-academy/ropes/image-sharing-project/basics-of-bootstrap-modals-js-and-ajax)
provides some background and code examples that will be really helpful for the
second PR, so it's worth watching (and following along) before you begin that
part.

__Discussion topics__:
- [ ] How could we develop the front end and back end separately? (And why
  might that be a good idea?)
- [ ] How should we implement a non-CRUD action?
- [ ] What are the different types of errors we should handle?
- [ ] What is AJAX? What libraries can help us add AJAX to our Rails app?
- [ ] How should we go about sending emails from our Rails app?
- [ ] How could we show a preview of the image being shared in the modal?
- [ ] What are the implications of allowing users to send emails from our app?

__Reference material__:
- http://guides.rubyonrails.org/action_mailer_basics.html
- https://elements.heroku.com/addons/sendgrid
- https://devcenter.heroku.com/articles/sendgrid#ruby-rails
- https://github.com/rails/jquery-ujs/wiki
- http://v4-alpha.getbootstrap.com/components/modal
- https://sites.google.com/a/appfolio.com/eng/new-hire-resources/engineering-academy/ropes/image-sharing-project/basics-of-bootstrap-modals-js-and-ajax

__Dependencies__:
- Image Index

**Comment by mqchau** [comment]
Can I create a new route like:
/images/1/share

Then has a form with email address to send to, body of message, the image and Send button?

This way I can reuse most of my set up for the form to create new image.

**Comment by rmacklin** [comment]
The recommendation for this story is to break it into two parts. In the first part you'd implement a page with a form to share the image, which will require separate GET and POST routes (I think this is what you may have been describing). In the second part you'd refactor it so that there is no "share page" but instead clicking on the share button just opens a modal with the share form, which only requires one POST route for the form to submit to (via XHR). I wouldn't recommend doing the second part until you have finished the Add Style story, because the second part relies heavily on bootstrap which is added in the Add Style story.

**Comment by mqchau** [comment]
Rubocop gives me error "Assignment Branch Condition size for email is too high". How do I fix this function?

```ruby
def email
    if mailValidator.valid?(share_params[:email_address])
      ImageMailer.image_email(share_params[:email_address], @image.link, share_params[:message]).deliver_now
      respond_to do |format|
        format.json { render json: {} }
      end
    else
      respond_to do |format|
        format.json { render json: { error: 'Invalid email' }, status: :unprocessable_entity }
      end
    end
end
```

**Comment by rmacklin** [comment]
If you work through this story in the recommended approach that I described above, you won't run into that issue (and there will be several other benefits). Please don't worry about JSON responses and modals until you've first implemented sharing as its own page (and please open a PR at that point).

**Comment by bboe** [comment]
> Bryce & I think

Do you mean Jon? Or are you extrapolating from our general conversation that the server side always needs to validate?

**Comment by mqchau** [comment]
Yes we discussed that server side always needs validate yesterday in our 1on1 session.

**Comment by rmacklin** [comment]
> I followed that path and got through the part with separate page already.

This is a good point to open a PR. You can immediately deliver value to your customers, and since the changeset is smaller, it'll be less likely to introduce bugs. We can completely review and QA the backend email delivery now, and then after you open a second PR to refactor to a modal, we'll only need to review and QA the new front end (and it's integration points with the backend). I'm curious, have you been to the Elephant Carpaccio Academy session yet?

**Comment by mqchau** [comment]
> have you been to the Elephant Carpaccio Academy session yet?
No I haven't

I agree that the separate share page is a good milestone to make a PR. Then we add modal box and make another PR. However I never used that PR pattern in any previous issue so I didn't plan it here. I will think about that next time. The issue of authorization seems to be another complicated one.

Anyway I got a fresh mind this morning and solved that error of ABC size:

```ruby
  def email
    email_address = share_params[:email_address]
    message = share_params[:message]
    respond_to do |format|
      if EmailValidator.valid?(email_address)
        ImageMailer.image_email(email_address, @image.link, message).deliver_now
        format.json { render json: {} }
      else
        format.json { render json: { error: 'Invalid email' }, status: :unprocessable_entity }
      end
    end
  end

```

**Comment by rmacklin** [comment]
> I agree that the separate share page is a good milestone to make a PR. Then we add modal box and make another PR. However I never used that PR pattern in any previous issue so I didn't plan it here.

It's totally okay that you didn't plan to open two PRs, but what I'm saying is for a more efficient review (and to deliver value sooner), I'd like you to open a PR from the commit that completes the sharing functionality before the commits that refactor to use a modal. All you'll need to do is:
```
git checkout <sha-before-refactor-to-modal-commits>
git checkout -b simple-sharing-feature
git push -u origin HEAD
```
and then open a PR on GitHub for that branch

**Comment by rmacklin** [comment]
> have you been to the Elephant Carpaccio Academy session yet?

> No I haven't

@bboe It _may_ make sense to move that session earlier. It would help them see the value in splitting bigger stories like this one. But maybe it's not necessary once background stories have been added to all the issues.
