### ISSUE TITLE
Image Tags

### ISSUE THREAD

**Issue by AppFolioRopes** [AppFolioOnboarding/image-sharer-mqchau#7]
#### As a user I want to add tags to images.

Acceptance criteria:
- [ ] When I add a new image, there is a form field to add tags.
- [ ] After I've saved an image with tags, I see those tags displayed with the
  associated image on the index page.
- [ ] My application uses the acts-as-taggable-on gem to provide the tagging
  functionality.

Reference material:
- https://github.com/mbleigh/acts-as-taggable-on

Dependencies:
- Image Index

**Comment by mqchau** [comment]
This ROPES project is using Rails 5.0.0, which depends on ActiveRecord = 5.0.0.
And acts-as-taggable-on latest version 3.5.0 depends on ActiveRecord < 5

That means at present, we can't use Rails 5.0.0 with acts-as-taggable-on.

What do you guys think? Should we rollback rails version to 4?

**Comment by bboe** [comment]
`gem 'acts-as-taggable-on', github: 'mbleigh/acts-as-taggable-on'`

Looks like using the latest master should work. See https://github.com/mbleigh/acts-as-taggable-on/pull/720

**Comment by bboe** [comment]
Actually, better yet.

`gem 'acts-as-taggable-on', '4.0.0.pre'
